# Remember position
save-position-on-quit=yes
volume=50
#Alignment#
video-align-y=-1
#sub-margin-y=115

# Better playlist behavior
watch-later-options-remove=fullscreen,volume,mute
write-filename-in-watch-later-config=yes
